/* Bodas — tabela 1 a 100 anos (lista mais usada no Brasil). [ano, nome, ícone, cor, significado curto, slug da página (se existir)] */
window.BODAS = [
[1,"Papel","papel","#b89b72","O papel é frágil e ainda em branco: é o começo da história que o casal vai escrever junto.","bodas-de-papel"],
[2,"Algodão","tecido","#a9b8c9","Macio e resistente, o algodão fala de um amor que ganhou conforto e se adapta ao dia a dia.","bodas-de-algodao"],
[3,"Couro","couro","#8a5a36","O couro é flexível e dura muito: o casal aprendeu a ceder sem se romper.","bodas-de-couro"],
[4,"Flores e Frutas","flor","#d0677a","Depois de plantar, o casal colhe: as flores e as frutas são os primeiros resultados da vida a dois.","bodas-de-flores-e-frutas"],
[5,"Madeira","arvore","#8b5a2b","Raízes firmes: a madeira representa uma união que já tem estrutura pra sustentar a casa.","bodas-de-madeira"],
[6,"Açúcar","doce","#d8a7b1","A doçura que continua depois da rotina: o carinho que adoça os dias comuns.","bodas-de-acucar"],
[7,"Lã","tecido","#b07a5a","A lã aquece e protege: o casal virou abrigo um do outro.","bodas-de-la"],
[8,"Barro","vaso","#a0522d","Barro se molda com as mãos: oito anos de ajustes deram forma à família.","bodas-de-barro"],
[9,"Cerâmica","vaso","#c26a3d","O barro foi ao forno e endureceu: a relação ganhou firmeza sem perder a beleza.","bodas-de-ceramica"],
[10,"Estanho","metal","#8e9aa6","Primeiro metal da lista: maleável e durável, marca uma década de amor.","bodas-de-estanho"],
[11,"Aço","metal","#6f7b86","O aço é forte e difícil de quebrar, como um casal que já passou por muita coisa.","bodas-de-aco"],
[12,"Seda","tecido","#b5485d","Fio delicado e ao mesmo tempo resistente: a elegância de um amor maduro.","bodas-de-seda"],
[13,"Linho","tecido","#a89a7a","Tecido nobre e natural: a simplicidade e a pureza de quem se conhece de verdade.","bodas-de-linho"],
[14,"Marfim","perola","#d9ccb0","Raro e valioso: o marfim fala de um amor que ficou precioso com o tempo.","bodas-de-marfim"],
[15,"Cristal","gema","#7fb2d6","Transparência e brilho: quinze anos de confiança sem nada a esconder.","bodas-de-cristal"],
[16,"Safira","gema","#1f4e9c","Pedra de lealdade: o azul da safira representa fidelidade e sabedoria.","bodas-de-safira"],
[17,"Rosa","rosa","#c9415e","A rosa é a flor do amor: dezessete anos e o romance continua florescendo.","bodas-de-rosa"],
[18,"Turquesa","gema","#1fa2a6","Pedra de proteção e sorte: um amor que cuida e atrai coisas boas.","bodas-de-turquesa"],
[19,"Cretone","tecido","#9b6b8e","Tecido forte e estampado: o casal que ganhou cor e resistência juntos.","bodas-de-cretone"],
[20,"Porcelana","xicara","#2f5d9a","Bonita, refinada e resistente ao calor: vinte anos de um amor que foi lapidado.","bodas-de-porcelana"],
[21,"Zircão","gema","#6b8fbf","Uma pedra que brilha como diamante: o amor que segue reluzindo.",null],
[22,"Louça","xicara","#4f7cac","A louça do dia a dia: o companheirismo das pequenas coisas compartilhadas.",null],
[23,"Palha","folha","#c7a24a","A palha é trançada fio a fio: uma vida entrelaçada com paciência.",null],
[24,"Opala","gema","#9fb7c9","Pedra de muitas cores: as fases diferentes que o casal viveu junto.",null],
[25,"Prata","metal","#9aa3ad","Um quarto de século: a prata é nobre, brilha e fica mais bonita com o cuidado.","bodas-de-prata"],
[26,"Alexandrita","gema","#5a7d5a","Pedra que muda de cor com a luz: um amor que se renova.",null],
[27,"Crisoprásio","gema","#5fae7d","Pedra verde de esperança: o casal que continua sonhando junto.",null],
[28,"Hematita","gema","#5b5b66","Pedra de equilíbrio e força: a calma de quem se entende no olhar.",null],
[29,"Erva","folha","#6d8f3b","A erva brota de novo depois de cortada: o amor que sempre renasce.",null],
[30,"Pérola","perola","#cfc3ae","A pérola nasce devagar, camada por camada: trinta anos de beleza construída.","bodas-de-perola"],
[31,"Nácar","perola","#d6cbbd","O brilho de dentro da concha: a beleza escondida que só o tempo revela.",null],
[32,"Pinho","arvore","#4f6b3a","Árvore que resiste ao frio: um casal que enfrenta junto as estações da vida.",null],
[33,"Crizo","gema","#c9a227","O brilho dourado de um amor que já é tesouro da família.",null],
[34,"Oliveira","folha","#7a8b4a","A oliveira dura séculos e dá frutos: símbolo de paz e de fartura.",null],
[35,"Coral","coral","#e2725b","O coral cresce devagar no fundo do mar: um amor que virou abrigo pra muita vida.","bodas-de-coral"],
[36,"Cedro","arvore","#7b4a2e","Madeira nobre e perfumada: a dignidade de uma união longa.",null],
[37,"Aventurina","gema","#3f8f5f","Pedra da sorte: o casal que sabe que teve sorte de se encontrar.",null],
[38,"Carvalho","arvore","#6b4a2a","O carvalho é símbolo de força e longevidade.",null],
[39,"Mármore","vaso","#b8b3ab","Firme e elegante: uma história que parece esculpida pra durar.",null],
[40,"Esmeralda","gema","#2e8b57","O verde da esperança: quarenta anos e a vontade de seguir juntos.","bodas-de-esmeralda"],
[41,"Seda Pura","tecido","#a8435a","A delicadeza que ficou ainda mais nobre com o tempo.",null],
[42,"Prata Dourada","metal","#bfa76a","A prata ganhou brilho de ouro: a união já é pura riqueza.",null],
[43,"Azeviche","gema","#2b2b2b","Pedra negra de proteção: o casal que se protege das tempestades.",null],
[44,"Carbonato","gema","#9aa6a0","A matéria que forma as rochas: a base sólida da família.",null],
[45,"Rubi","gema","#9b111e","O vermelho do rubi é paixão que não apagou em quarenta e cinco anos.","bodas-de-rubi"],
[46,"Alabastro","vaso","#e0d6c3","Pedra clara e luminosa: a serenidade de um amor maduro.",null],
[47,"Jaspe","gema","#a0472e","Pedra de coragem e de proteção.",null],
[48,"Granito","vaso","#7d7a75","Uma das pedras mais duras: uma união que o tempo não desgasta.",null],
[49,"Heliotrópio","gema","#3d6b4a","A pedra que segue o sol: o casal que continua olhando na mesma direção.",null],
[50,"Ouro","metal","#c9a227","Meio século: o ouro não enferruja, não perde o valor e brilha pra sempre.","bodas-de-ouro"],
[51,"Bronze","metal","#a0672e","Metal de monumentos: uma história que merece ser lembrada.",null],
[52,"Argila","vaso","#b5653a","A matéria-prima da vida: a família que nasceu desse amor.",null],
[53,"Antimônio","metal","#8a8f96","Um metal raro, como uma união de mais de cinquenta anos.",null],
[54,"Níquel","metal","#9ea4a8","Metal que resiste ao tempo e à corrosão.",null],
[55,"Ametista","gema","#8e5bbd","Pedra da serenidade e da sabedoria: cinquenta e cinco anos de paz a dois.","bodas-de-ametista"],
[56,"Malaquita","gema","#1f7a5a","Pedra verde de transformação: o casal que mudou junto sem se perder.",null],
[57,"Lápis-lazúli","gema","#26619c","Pedra azul da verdade e da amizade.",null],
[58,"Vidro","taca","#7fb6c4","Transparente e luminoso: nada a esconder depois de tanto tempo.",null],
[59,"Cereja","fruta","#b0203a","O fruto doce da maturidade.",null],
[60,"Diamante","gema","#8fb8d8","A pedra mais dura e mais brilhante: sessenta anos de um amor indestrutível.","bodas-de-diamante"],
[61,"Cobre","metal","#b87333","Metal que conduz energia: o afeto que ainda passa de um pro outro.",null],
[62,"Telurita","gema","#8a8a7a","Um mineral raro, como uma união tão longa.",null],
[63,"Sândalo","arvore","#8b5e3c","Madeira perfumada: o amor que deixa um cheiro bom por onde passa.",null],
[64,"Fabulita","gema","#a9c4d8","O brilho de uma história que parece de fábula.",null],
[65,"Platina","metal","#a7adb3","Mais rara que o ouro: sessenta e cinco anos juntos é para poucos.","bodas-de-platina"],
[66,"Ébano","arvore","#3a2a20","Madeira escura e nobríssima, das mais resistentes.",null],
[67,"Neve","neve","#9fc0d6","A pureza e a calma de quem já viveu muito junto.",null],
[68,"Chumbo","metal","#6a6f74","Metal pesado: o peso bom de uma história tão longa.",null],
[69,"Mercúrio","metal","#9aa0a6","O metal que se move: um amor que continua vivo.",null],
[70,"Vinho","taca","#7b1e3a","Como o vinho, o amor melhorou com o tempo.","bodas-de-vinho"],
[71,"Zinco","metal","#8c969e","Metal que protege outros metais da ferrugem.",null],
[72,"Aveia","folha","#b8a25a","O alimento simples de todo dia: o cuidado que nunca faltou.",null],
[73,"Manjerona","folha","#6f8f4f","Erva de felicidade e bem-estar.",null],
[74,"Macieira","fruta","#c0392b","A árvore que dá frutos ano após ano.",null],
[75,"Brilhante","gema","#9cc3dd","O diamante lapidado: setenta e cinco anos de um amor que brilha.","bodas-de-brilhante"],
[76,"Cipreste","arvore","#3f5f45","Árvore que vive por séculos e fica verde o ano inteiro.",null],
[77,"Alfazema","flor","#8a73b8","O perfume calmo de uma vida inteira juntos.",null],
[78,"Benjoim","arvore","#8b6b4a","Resina perfumada e rara.",null],
[79,"Café","xicara","#6f4e37","O café de todo dia, tomado juntos há quase oitenta anos.",null],
[80,"Carvalho","arvore","#6b4a2a","Oitenta anos: força e longevidade como a do carvalho.",null],
[81,"Cacau","doce","#7b4b2a","O sabor doce de uma vida compartilhada.",null],
[82,"Cravo","flor","#c0392b","Flor de afeto e admiração.",null],
[83,"Begônia","flor","#d9667a","Flor de delicadeza e cordialidade.",null],
[84,"Crisântemo","flor","#d4a017","Flor de longevidade e alegria.",null],
[85,"Girassol","flor","#e0a800","A flor que sempre procura a luz.",null],
[86,"Hortênsia","flor","#6c8ebf","Flor de gratidão e compreensão.",null],
[87,"Nogueira","arvore","#6b4e2e","Árvore de madeira nobre e frutos generosos.",null],
[88,"Pera","fruta","#9bab3a","O fruto maduro de uma vida inteira.",null],
[89,"Figueira","fruta","#6b4a6b","Árvore de fartura e de abrigo.",null],
[90,"Álamo","arvore","#5f7a4a","Árvore alta que cresce em direção ao céu.",null],
[91,"Pinheiro","arvore","#3f6b45","Sempre verde, em qualquer estação.",null],
[92,"Salgueiro","arvore","#6f8f5f","Árvore flexível que se curva sem quebrar.",null],
[93,"Imbuia","arvore","#5e3b24","Madeira nobre brasileira, rara e duradoura.",null],
[94,"Palmeira","arvore","#4f7f3f","Árvore que resiste ao vento.",null],
[95,"Sândalo","arvore","#8b5e3c","Perfume que atravessa gerações.",null],
[96,"Oliveira","folha","#7a8b4a","Paz e fartura depois de quase um século.",null],
[97,"Abeto","arvore","#2f5a45","Árvore que vive muito e não perde as folhas.",null],
[98,"Pinheiro","arvore","#3f6b45","A firmeza de quem atravessou quase cem invernos.",null],
[99,"Salgueiro","arvore","#6f8f5f","A flexibilidade que fez a união durar.",null],
[100,"Jequitibá","arvore","#4a6b35","A maior árvore da mata brasileira: um século de amor.",null]
];
