# -*- coding: utf-8 -*-
# Conteúdo único por boda (1 a 10 anos). Cada página tem significado, origem, presentes, frases, como comemorar e FAQ próprios.
C = {}

C[1] = dict(
intro="Um ano de casados são as <b>Bodas de Papel</b>. É a primeira boda da lista e, justamente por isso, a mais simbólica: o casamento ainda é uma folha nova, com muito espaço pra escrever.",
sig=["O papel foi escolhido porque é leve, frágil e aceita tudo o que se escreve nele. No primeiro ano, o casal ainda está aprendendo a morar junto, a dividir as contas, a lidar com a família um do outro. Nada está pronto, e isso é bonito: é o ano em que a história começa a ganhar as primeiras linhas.",
"Tem também um lado prático. O papel rasga fácil, então a boda lembra que o começo precisa de cuidado. Mas, dobrado várias vezes, fica resistente — como uma relação que vai ganhando camadas de confiança."],
origem="A tradição de dar nome a cada aniversário de casamento vem da Europa, onde as bodas de prata (25 anos) e de ouro (50) já eram festejadas na Idade Média. A lista completa, com um material pra cada ano, foi sendo montada no século 20, e o papel ficou no primeiro degrau por ser o material mais simples e acessível. Em alguns países, o 1º ano também aparece como \"bodas de algodão\", mas no Brasil o papel é unanimidade.",
presentes=[("Carta escrita à mão","O presente mais óbvio e o que mais emociona. Conte o que mudou no primeiro ano e o que você quer pro segundo."),
("Livro com dedicatória","Aquele livro que tem a ver com a história de vocês, com uma dedicatória na primeira página e a data."),
("Álbum ou fotolivro do 1º ano","Casamento, lua de mel, primeira casa: um ano rende fotos demais pra ficarem só no celular."),
("Ingressos","Show, teatro, cinema ou jogo. É papel, é experiência e vira memória."),
("Quadro das Bodas de Papel","Com os nomes, a data e o número de dias juntos. Fica na parede como o primeiro marco da casa."),
("Mapa das estrelas ou do lugar onde se conheceram","Impresso e emoldurado, é papel com significado.")],
frases=[("Pro marido ou pra esposa","Um ano atrás a gente assinou um papel. Hoje eu assinaria de novo, sem ler as letras miúdas. Feliz Bodas de Papel, meu amor."),
("Pro casal amigo","Primeiro capítulo concluído! Que venham muitos anos de páginas bonitas pra vocês dois. Parabéns pelas Bodas de Papel."),
("Legenda curta","1 ano, 365 dias e uma folha ainda cheia de espaço pra escrever. Bodas de Papel 🤍"),
("Pro cartão","Que este papel guarde o que a gente viveu em um ano: as risadas, as mudanças e a certeza de que escolhi bem."),
("Pros filhos ou netos casados","Um ano de casados e a gente já vê como vocês cuidam um do outro. Que o papel vire ouro. Parabéns!")],
comemorar=["Refazer o primeiro encontro: mesmo lugar, mesma comida, mesma roupa se ainda couber.","Abrir a garrafa ou o topo do bolo guardado do casamento (se sobreviveu ao freezer).","Escrever uma carta um pro outro e guardar pra abrir nas Bodas de Estanho, aos 10 anos.","Um jantar em casa com a playlist da festa de casamento."],
faq=[("Bodas de papel é com 1 ano ou 1 mês?","Com 1 ano de casados. As listas de \"bodas mensais\" (de namoro) são outra coisa e variam muito; a tradição do casamento conta anos."),
("O que dar de presente de bodas de papel barato?","Carta à mão, fotos impressas, ingressos ou um quadro personalizado pra imprimir em casa. O que vale é o simbolismo do papel, não o preço.")])

C[2] = dict(
intro="Dois anos de casados são as <b>Bodas de Algodão</b>. Depois do papel, o casamento ganha um material mais macio e mais resistente.",
sig=["O algodão é fibra natural, maleável e confortável. No segundo ano, a rotina já está mais ajustada: cada um sabe como o outro gosta do café, quem acorda primeiro, quem esquece a luz acesa. O casal começou a se sentir em casa um com o outro.",
"Também é um lembrete: algodão precisa ser trançado pra virar tecido. É fio a fio, com paciência, que os dois vão tecendo a vida juntos."],
origem="O algodão aparece no segundo ano em quase todas as listas do Ocidente. Nos Estados Unidos ele é o presente \"oficial\" de dois anos; em Portugal e no Brasil a correspondência é a mesma. É uma evolução natural do papel: ainda simples, mas já mais durável.",
presentes=[("Jogo de cama ou lençol bom","Aquele de fio egípcio que ninguém compra pra si mesmo. Presente que se usa todo dia."),
("Roupão ou pijamas combinando","Divertido, confortável e fotogênico."),
("Camiseta personalizada","Com a data do casamento, uma piada interna ou o nome do pet."),
("Toalhas bordadas com as iniciais","Clássico que nunca erra, principalmente pra dar a um casal."),
("Manta de sofá","Pra noite de filme a dois."),
("Quadro das Bodas de Algodão","Com os nomes e os 730 dias juntos, pra pendurar no quarto.")],
frases=[("Pro amor","Dois anos e você continua sendo o lugar mais confortável que eu conheço. Feliz Bodas de Algodão."),
("Pro casal","Que a vida de vocês continue macia como algodão e forte como o que vocês construíram até aqui. Parabéns pelos 2 anos!"),
("Legenda curta","2 anos de casados: menos cerimônia, mais conchinha. Bodas de Algodão ☁️"),
("Pro cartão","Fio por fio, dia por dia, a gente vai tecendo uma vida que é só nossa."),
("Pra quem teve um ano difícil","Não foi um ano fácil, mas foi o ano em que eu tive certeza de que com você eu atravesso qualquer coisa.")],
comemorar=["Piquenique no parque com uma toalha xadrez de algodão (o clichê funciona).","Dia inteiro de pijama, filme e comida pedida.","Plantar algo juntos: a planta cresce junto com o casamento.","Renovar o enxoval: trocar o lençol velho do começo do casamento por um novo, escolhido a dois."],
faq=[("Bodas de algodão são quantos anos?","2 anos de casados, logo depois das Bodas de Papel (1 ano)."),
("Presente de bodas de algodão precisa ser de algodão?","Não precisa, mas é a graça. Roupa de cama, toalha e roupas são os mais comuns; uma carta ou um quadro com o tema também valem.")])

C[3] = dict(
intro="Três anos de casados são as <b>Bodas de Couro</b>. Em algumas listas antigas aparece como bodas de trigo, mas o couro é o nome mais usado no Brasil.",
sig=["O couro é resistente, mas flexível: dobra, estica e volta ao lugar. Aos três anos, o casal já passou pelas primeiras brigas de verdade e aprendeu a ceder sem se romper. A relação ficou mais firme justamente porque aprendeu a ser maleável.",
"E couro bom melhora com o uso: ganha marcas, amacia, fica com a cara do dono. Um casamento de três anos também já tem as suas marcas — e elas contam a história de vocês."],
origem="Os presentes de couro no terceiro aniversário ficaram populares nos Estados Unidos e na Inglaterra no século 20 e chegaram ao Brasil junto com a lista completa de bodas. O trigo, que aparece em listas portuguesas, fala da mesma ideia: o casal que começa a colher o que plantou.",
presentes=[("Carteira, cinto ou bolsa","O óbvio que acerta. Dá pra gravar as iniciais."),
("Capa de passaporte e tag de mala","Pra quem ama viajar: um convite pra próxima viagem a dois."),
("Caderno de couro","Pra registrar planos, receitas ou o diário do casal."),
("Pulseiras de couro combinando","Discreto e simbólico."),
("Porta-retrato de couro","Com uma foto dos três anos."),
("Quadro das Bodas de Couro","Com a data e os mais de mil dias juntos.")],
frases=[("Pro amor","Três anos aprendendo a ceder, a esperar e a recomeçar. Como o couro, a gente ficou mais forte dobrando junto."),
("Pro casal","Três anos de casados! Que o amor de vocês continue resistente e confortável como couro bom."),
("Legenda curta","3 anos e mais de mil dias juntos. Bodas de Couro 🤎"),
("Pro cartão","Obrigado pelas vezes em que você cedeu, e pelas vezes em que me ensinou a ceder."),
("Pra um casal com filho pequeno","Três anos, uma casa cheia e muito sono atrasado. Vocês são incríveis. Parabéns pelas Bodas de Couro!")],
comemorar=["Uma viagem curta de carro ou de moto, só os dois.","Jantar num restaurante de carnes ou numa churrascaria (o tema pede).","Fazer um álbum dos 3 anos, com uma foto de cada mês marcante.","Escolher juntos um objeto de couro pra casa, como uma poltrona ou um puff, que vai envelhecer com vocês."],
faq=[("3 anos de casados são bodas de quê?","Bodas de Couro. Algumas listas trazem bodas de trigo para o mesmo ano."),
("O que dar nas bodas de couro para o marido?","Carteira ou cinto com as iniciais, capa de passaporte, pulseira ou um quadro personalizado com a data do casamento.")])

C[4] = dict(
intro="Quatro anos de casados são as <b>Bodas de Flores e Frutas</b> — em algumas listas, bodas de cera. É uma das bodas mais bonitas de comemorar.",
sig=["Depois de plantar (papel), cuidar (algodão) e firmar as raízes (couro), o casal começa a colher. As flores representam o que o casamento tem de bonito e delicado; as frutas, os resultados concretos: a casa montada, os planos que saíram do papel, às vezes o primeiro filho.",
"É uma boda de fartura e de cor. E um bom lembrete: flor murcha sem água, e fruta só vem com paciência."],
origem="A combinação \"flores e frutas\" é típica das listas brasileiras e portuguesas. Nos Estados Unidos, o quarto ano é associado a frutas e flores ou a linho; em algumas listas antigas aparece a cera, símbolo da luz que ilumina a casa.",
presentes=[("Buquê ou arranjo","Com as flores do buquê de noiva, se der pra lembrar quais eram."),
("Cesta de frutas e café da manhã","Entregue na cama, de preferência."),
("Assinatura de flores","Um buquê por mês até as bodas de madeira."),
("Uma árvore frutífera","Pra plantar no quintal ou num vaso grande. Vai dar fruto junto com o casamento."),
("Joia com flor","Colar ou brinco com pingente de flor."),
("Quadro das Bodas de Flores e Frutas","No estilo floral, com os nomes e os 1.461 dias juntos.")],
frases=[("Pro amor","Quatro anos depois, olho pro que a gente plantou e só vejo flor. Feliz Bodas de Flores e Frutas."),
("Pro casal","Que a vida de vocês continue florida e cheia de frutos. Parabéns pelos 4 anos de casados!"),
("Legenda curta","4 anos: tempo de colher. Bodas de Flores e Frutas 🌸🍓"),
("Pro cartão","Você é a flor dos meus dias e a razão de tudo o que a gente já colheu."),
("Pros filhos casados","Que alegria ver o jardim que vocês estão cultivando. Parabéns pelos 4 anos!")],
comemorar=["Piquenique com frutas da estação e flores na toalha.","Visitar um jardim botânico, um orquidário ou uma fazenda de colher morango.","Fazer um drinque ou uma sobremesa só com frutas, juntos na cozinha.","Recriar o buquê do casamento pra uma foto nova."],
faq=[("Bodas de 4 anos é flores e frutas ou cera?","As duas aparecem, mas Flores e Frutas é a mais usada no Brasil. A cera vem de listas mais antigas."),
("Que flor dar nas bodas de flores e frutas?","As do buquê de noiva são a escolha mais emocionante. Se não souber, rosas (amor), girassóis (alegria) ou flores do campo funcionam bem.")])

C[5] = dict(
intro="Cinco anos de casados são as <b>Bodas de Madeira</b>. É a primeira grande boda: meia década juntos.",
sig=["A madeira fala de estrutura. Uma árvore precisa de anos pra ter um tronco firme, e aos cinco anos o casamento também já tem: raízes que seguram nos dias de vento, casa organizada, uma vida que ficou de pé.",
"Madeira também é material de construção. É com ela que se faz a mesa onde a família come, a porta que protege, o berço. É por isso que a boda de cinco anos costuma ser comemorada com mais festa que as anteriores."],
origem="As bodas de madeira são uma das mais antigas da lista. A madeira aparece no quinto ano em praticamente todas as tradições do Ocidente, porque o número cinco já era visto como um primeiro marco de estabilidade.",
presentes=[("Tábua de frios gravada","Com os nomes e a data. Bonita, útil e vai durar."),
("Relógio de madeira","Tempo e madeira no mesmo presente."),
("Caixa de memórias","Pra guardar cartas, ingressos e fotos dos cinco anos."),
("Uma muda de árvore","Pra plantar e acompanhar o crescimento — o mais simbólico de todos."),
("Móvel feito sob medida","Uma estante, uma mesa de cabeceira, um banco pra varanda."),
("Quadro das Bodas de Madeira","Numa moldura de madeira, com os nomes e os mais de 1.800 dias juntos.")],
frases=[("Pro amor","Cinco anos e raízes cada vez mais fundas. Com você eu construí a casa que eu queria. Feliz Bodas de Madeira."),
("Pro casal","Meia década de casados! Que a madeira de vocês continue firme e dê muita sombra boa. Parabéns!"),
("Legenda curta","5 anos, raízes firmes. Bodas de Madeira 🌳"),
("Pro cartão","A gente se escolheu, se plantou e cresceu junto. Que venham os próximos cinco."),
("Pros pais","Cinco anos de casamento de vocês e já dá pra ver a árvore bonita que está nascendo aqui. Parabéns!")],
comemorar=["Plantar uma árvore num lugar que vocês visitem sempre.","Um fim de semana num chalé de madeira na serra.","Renovar os votos num jardim, só com a família mais próxima.","Montar juntos um móvel ou uma horta de madeira pra casa."],
faq=[("5 anos de casados são bodas de quê?","Bodas de Madeira, a primeira grande boda do casamento."),
("Como comemorar bodas de madeira de forma simples?","Plantar uma árvore, preparar um jantar em casa com mesa de madeira e velas, e dar um presente gravado ou um quadro com a data.")])

C[6] = dict(
intro="Seis anos de casados são as <b>Bodas de Açúcar</b> (em algumas listas, bodas de perfume). É a boda do carinho que continua depois da rotina.",
sig=["O açúcar entra aqui pra lembrar que, mesmo com contas, filhos, trabalho e cansaço, o casamento precisa de doçura. Aos seis anos a paixão do começo já deu lugar a outra coisa: o carinho do dia a dia, as pequenas gentilezas que adoçam uma terça-feira comum.",
"E açúcar derrete no calor, então a boda também pede atenção: doçura se renova, não fica guardada no pote."],
origem="As bodas de açúcar são típicas das listas brasileiras. Em algumas versões portuguesas o sexto ano é o do perfume, com o mesmo espírito: algo que deixa a vida mais agradável. Nos Estados Unidos, o sexto ano é o do ferro, bem diferente do nosso.",
presentes=[("Cesta de doces artesanais","Brigadeiros gourmet, doces da infância ou os doces servidos no casamento."),
("Aula de confeitaria a dois","Experiência, risada e sobremesa no final."),
("Bolo igual ao do casamento","Encomendado na mesma confeitaria, se ela ainda existir."),
("Perfume","Pra quem segue a outra tradição da boda."),
("Kit de chocolates finos e vinho","Pra uma noite especial em casa."),
("Quadro das Bodas de Açúcar","Com os nomes e uma frase doce no lugar do significado.")],
frases=[("Pro amor","Seis anos e você continua sendo a parte mais doce dos meus dias. Feliz Bodas de Açúcar."),
("Pro casal","Que nunca falte doçura na casa de vocês. Parabéns pelos 6 anos de casados!"),
("Legenda curta","6 anos de casados e ainda dividindo a sobremesa. Bodas de Açúcar 🍬"),
("Pro cartão","A vida ficou mais doce desde que você chegou. E continua ficando."),
("Divertida","Seis anos aguentando meu mau humor antes do café. Isso é que é amor doce.")],
comemorar=["Tour pelas docerias da cidade num sábado à tarde.","Fazer juntos a receita de doce da família de cada um.","Um café da manhã caprichado com bolo e frutas.","Repetir a sobremesa do casamento num jantar a dois."],
faq=[("Bodas de 6 anos é açúcar ou perfume?","As duas aparecem nas listas. Açúcar é a mais comum no Brasil."),
("O que dar de presente de 6 anos de casado?","Doces artesanais, uma aula de confeitaria, perfume ou um quadro de bodas personalizado.")])

C[7] = dict(
intro="Sete anos de casados são as <b>Bodas de Lã</b> (ou de latão, em algumas listas). É a boda do aconchego.",
sig=["A lã aquece e protege do frio. Aos sete anos o casal virou abrigo: é pra casa, pro abraço do outro, que cada um volta depois de um dia ruim. A relação ganhou uma camada de proteção que só o tempo dá.",
"Os sete anos também carregam a fama da \"crise dos sete anos\". A boda de lã responde com carinho: é hora de se aquecer, não de se afastar."],
origem="A lã aparece no sétimo ano nas listas norte-americanas e brasileiras; o latão, em algumas listas portuguesas. O número sete, visto como número de plenitude em várias culturas, reforça a ideia de um ciclo completo.",
presentes=[("Manta ou cobertor de lã","Pro sofá, pra noite de filme."),
("Suéter, cachecol ou luvas","Se o aniversário cai no inverno, perfeito."),
("Meias quentinhas combinando","Divertido e útil."),
("Viagem pra serra","Lareira, fondue e cobertor."),
("Tapete de lã pra casa","Um presente pro lar dos dois."),
("Quadro das Bodas de Lã","Com os nomes e os mais de 2.500 dias juntos.")],
frases=[("Pro amor","Sete anos e o seu abraço continua sendo o lugar mais quentinho do mundo. Feliz Bodas de Lã."),
("Pro casal","Crise dos sete anos? Só se for de amor. Parabéns pelas Bodas de Lã!"),
("Legenda curta","7 anos de casados, aquecendo um ao outro. Bodas de Lã 🧶"),
("Pro cartão","Nos dias frios, é pra você que eu volto."),
("Pros filhos casados","Que a casa de vocês seja sempre quentinha de amor. Parabéns pelos 7 anos!")],
comemorar=["Um fim de semana numa pousada com lareira.","Noite de fondue em casa, com manta e filme.","Aprender tricô ou crochê juntos (vale a risada).","Um piquenique de inverno com chocolate quente."],
faq=[("7 anos de casados são bodas de quê?","Bodas de Lã. Algumas listas trazem bodas de latão."),
("Existe mesmo a crise dos sete anos?","É mais fama do que regra. Mas é um bom momento pra olhar pra relação com carinho e investir em tempo a dois.")])

C[8] = dict(
intro="Oito anos de casados são as <b>Bodas de Barro</b> (em algumas listas, de papoula). É a boda de quem já deu forma à vida em família.",
sig=["O barro é matéria-prima: com as mãos, vira pote, tijolo, vaso. Em oito anos o casal moldou muita coisa junto — a casa, os hábitos, os filhos, o jeito de resolver problema. Cada um também foi moldado um pouco pelo outro.",
"O barro ainda está úmido, dá pra corrigir, ajustar, recomeçar a peça. É uma boda que valoriza a paciência e o trabalho manual do dia a dia."],
origem="As bodas de barro são tradição das listas brasileiras e portuguesas, que costumam seguir uma sequência: barro aos 8, cerâmica aos 9 (o barro que foi ao forno). A papoula aparece em listas alternativas.",
presentes=[("Aula de cerâmica a dois","A cena do filme Ghost, com menos drama e mais risada."),
("Vaso de barro com uma planta","Símbolo vivo e barato."),
("Filtro de barro","Clássico brasileiro, presente útil e com história."),
("Panela de barro","Pra uma moqueca a dois."),
("Peça de artesanato de ceramista local","Única, como o casal."),
("Quadro das Bodas de Barro","Com os nomes, a data e os 2.922 dias juntos.")],
frases=[("Pro amor","Oito anos moldando uma vida com as mãos e o coração. Feliz Bodas de Barro, meu amor."),
("Pro casal","Que o que vocês moldaram juntos dure pra sempre. Parabéns pelos 8 anos!"),
("Legenda curta","8 anos dando forma a uma vida a dois. Bodas de Barro 🏺"),
("Pro cartão","A gente se moldou um ao outro sem deixar de ser quem é. Isso é raro."),
("Pros irmãos casados","Oito anos de casa, de família e de muita parceria. Vocês são exemplo!")],
comemorar=["Aula de cerâmica ou de torno pra fazer duas canecas.","Moqueca ou comida mineira em panela de barro.","Visitar uma feira de artesanato e escolher uma peça pra casa.","Viagem pra uma cidade histórica, com casas de barro e taipa."],
faq=[("8 anos de casados são bodas de quê?","Bodas de Barro. Em listas alternativas aparece a papoula."),
("Qual a diferença entre bodas de barro e de cerâmica?","Barro (8 anos) é a matéria-prima ainda moldável. Cerâmica (9 anos) é o barro que foi ao forno e endureceu.")])

C[9] = dict(
intro="Nove anos de casados são as <b>Bodas de Cerâmica</b> (ou de vime, em algumas listas). É o barro dos oito anos, agora cozido no forno.",
sig=["Barro vira cerâmica no fogo. Aos nove anos, o casal já passou por fases quentes — mudanças, perdas, filhos, trabalho — e saiu mais firme. A relação endureceu no bom sentido: ganhou forma definitiva sem perder a beleza.",
"A cerâmica é resistente, mas pede cuidado: um tombo e quebra. A boda lembra que o que é firme também merece delicadeza."],
origem="A cerâmica aos 9 anos completa a dupla com o barro dos 8 nas listas brasileiras. O vime, que aparece em outras listas, também é trançado e flexível — a ideia é parecida: algo feito com trabalho manual e paciência.",
presentes=[("Jogo de xícaras ou pratos artesanais","Pra usar todo dia e lembrar da data."),
("Canecas personalizadas","Com os nomes ou uma piada interna."),
("Vaso de cerâmica pintado","Com flores dentro."),
("Aula de pintura em cerâmica","Cada um pinta a peça do outro."),
("Cesto de vime com café da manhã","Pra quem segue a outra tradição."),
("Quadro das Bodas de Cerâmica","Com os nomes e os mais de 3.200 dias juntos.")],
frases=[("Pro amor","Nove anos passando pelo fogo e saindo mais fortes. Feliz Bodas de Cerâmica."),
("Pro casal","Que o amor de vocês continue firme e bonito como cerâmica. Parabéns pelos 9 anos!"),
("Legenda curta","9 anos: o barro foi pro forno e virou cerâmica. 🏺"),
("Pro cartão","A gente já passou por muita coisa quente. E olha como ficou bonito."),
("Um ano antes dos 10","Falta só um ano pra década! Obrigado por estes nove.")],
comemorar=["Aula de pintura em cerâmica com vinho.","Comprar um jogo de louça novo pra casa, escolhido juntos.","Jantar com a família usando a louça do enxoval.","Começar a planejar a festa dos 10 anos."],
faq=[("9 anos de casados são bodas de quê?","Bodas de Cerâmica. Algumas listas trazem bodas de vime."),
("Qual presente dar nas bodas de cerâmica?","Canecas, xícaras e vasos artesanais, uma aula de pintura em cerâmica ou um quadro personalizado.")])

C[10] = dict(
intro="Dez anos de casados são as <b>Bodas de Estanho</b> (em algumas listas, de zinco). Uma década juntos — é o primeiro metal da lista.",
sig=["Até aqui as bodas foram materiais naturais e mais frágeis. Aos 10 anos entra o primeiro metal: o estanho, maleável e durável, que não enferruja. É a boda que marca a passagem pra uma fase de solidez.",
"O estanho é usado pra soldar outros metais. Faz sentido: dez anos depois, o casal está soldado, unido de um jeito que não se desfaz com facilidade."],
origem="O estanho aos dez anos aparece nas listas dos Estados Unidos, de Portugal e do Brasil. É uma das bodas mais festejadas depois das de prata e ouro, justamente por fechar a primeira década.",
presentes=[("Viagem de 10 anos","Uma segunda lua de mel, nem que seja de fim de semana."),
("Peça de estanho","Porta-retrato, caneca ou castiçal de estanho, que é tradição."),
("Joia nova","Uma aliança de compromisso ou um anel pra marcar a década."),
("Álbum da década","Uma foto por ano, do casamento até hoje."),
("Renovação de votos","Pequena, íntima, com quem esteve lá há dez anos."),
("Quadro das Bodas de Estanho","Com os nomes, a data e os mais de 3.600 dias juntos.")],
frases=[("Pro amor","Dez anos e eu ainda escolheria você em todas as versões da minha vida. Feliz Bodas de Estanho."),
("Pro casal","Uma década de casados! Que venham muitas outras. Parabéns pelas Bodas de Estanho!"),
("Legenda curta","10 anos, 3.652 dias e o mesmo sorriso. Bodas de Estanho ✨"),
("Pro cartão","Em dez anos a gente mudou de casa, de emprego e de planos. Só não mudou a vontade de estar junto."),
("Pros pais","Dez anos do casamento de vocês e a gente cresceu vendo esse amor. Parabéns!")],
comemorar=["Renovar os votos com um almoço pra família e os padrinhos.","Refazer a viagem de lua de mel.","Uma festa com a playlist do casamento e as fotos da década no telão.","Abrir a carta escrita nas Bodas de Papel, se vocês fizeram isso."],
faq=[("10 anos de casados são bodas de quê?","Bodas de Estanho, o primeiro metal da lista. Algumas listas trazem bodas de zinco."),
("Bodas de estanho é festa grande?","Muitos casais fazem festa ou renovam os votos aos 10 anos, por ser a primeira década. Mas um jantar a dois com um presente simbólico também é lindo.")])
