# -*- coding: utf-8 -*-
# Conteúdo único por boda (11 a 20 anos).
C = {}

C[11] = dict(
intro="Onze anos de casados são as <b>Bodas de Aço</b>. Depois do estanho, o casamento ganha um metal ainda mais forte.",
sig=["O aço é uma liga: ferro e carbono que, juntos, ficam muito mais resistentes do que separados. É uma imagem bonita pra um casal de 11 anos — duas pessoas diferentes que, misturadas, viraram algo difícil de quebrar.",
"O aço também é o material das estruturas: pontes, prédios, trilhos. Onze anos depois, o casamento é estrutura pra muita coisa ao redor, da família aos amigos."],
origem="As bodas de aço aparecem no 11º ano nas listas do Brasil e de Portugal. Nos Estados Unidos, o aço também é associado ao 11º aniversário. É a boda que abre a segunda década.",
presentes=[("Relógio de aço","Resistente e pra usar todo dia."),
("Joia de aço cirúrgico gravada","Pulseira ou colar com a data do casamento."),
("Garrafa térmica ou jogo de panelas bons","Para um casal que curte cozinhar junto."),
("Faqueiro ou kit de churrasco","Aço que vai durar tanto quanto o casamento."),
("Experiência radical","Tirolesa, rapel, kart: coragem de aço."),
("Quadro das Bodas de Aço","No estilo Moderno, com os nomes e os mais de 4.000 dias juntos.")],
frases=[("Pro amor","Onze anos e a gente virou liga: juntos, muito mais fortes. Feliz Bodas de Aço."),
("Pro casal","Que nada abale o amor de vocês, forte como aço. Parabéns pelos 11 anos!"),
("Legenda curta","11 anos de casados, forjados no dia a dia. Bodas de Aço ⚙️"),
("Pro cartão","Já passamos por fogo e martelo. E olha a gente aqui, mais firmes."),
("Pra um casal que superou uma fase difícil","Vocês mostraram que amor de verdade é de aço. Parabéns pelos 11 anos!")],
comemorar=["Uma aventura diferente: trilha, rafting ou voo de balão.","Jantar num restaurante novo, fora da rotina.","Visitar uma ponte ou um mirante bonito da cidade e tirar uma foto nova.","Começar um projeto juntos pra essa segunda década."],
faq=[("11 anos de casados são bodas de quê?","Bodas de Aço, a boda que abre a segunda década."),
("Presente de bodas de aço pra esposa?","Joia de aço gravada, relógio, uma experiência a dois ou um quadro personalizado com a data.")])

C[12] = dict(
intro="Doze anos de casados são as <b>Bodas de Seda</b> (em algumas listas, de ônix). É a boda da delicadeza que resiste.",
sig=["A seda é um dos tecidos mais finos que existem e, ao mesmo tempo, um dos fios naturais mais resistentes. Doze anos depois, o casal aprendeu isso: dá pra ser delicado e forte ao mesmo tempo.",
"Seda também leva tempo pra ser produzida, fio por fio, pelo bicho-da-seda. É um amor que foi tecido com paciência e ficou elegante."],
origem="A seda aparece no 12º ano nas listas brasileiras e em várias europeias; o ônix, pedra preta de proteção, é a alternativa em algumas listas. A seda, por ter vindo do Oriente pela Rota da Seda, sempre foi sinônimo de luxo.",
presentes=[("Lenço ou gravata de seda","Clássico e elegante."),
("Pijama ou camisola de seda","Romântico e confortável."),
("Fronhas de seda","Presente de autocuidado a dois."),
("Máscara de dormir de seda","Pra quem sonha com uma viagem."),
("Joia com ônix","Pra quem segue a outra tradição."),
("Quadro das Bodas de Seda","Com os nomes e os mais de 4.300 dias juntos.")],
frases=[("Pro amor","Doze anos de um amor delicado como seda e forte como ela. Feliz Bodas de Seda."),
("Pro casal","Que a vida de vocês continue suave e elegante. Parabéns pelos 12 anos!"),
("Legenda curta","12 anos de casados, fio por fio. Bodas de Seda 🎀"),
("Pro cartão","A gente teceu uma vida bonita. E ainda tem muito fio pra frente."),
("Pros pais","Doze anos e o carinho de vocês continua delicado como no começo. Parabéns!")],
comemorar=["Jantar elegante, com roupa de gala, mesmo que seja em casa.","Um dia de spa a dois.","Aula de dança de salão.","Uma noite num hotel bonito na própria cidade."],
faq=[("12 anos de casados são bodas de quê?","Bodas de Seda. Algumas listas trazem bodas de ônix."),
("O que simboliza a seda nas bodas?","Delicadeza e resistência ao mesmo tempo: um tecido fino, mas de fio muito forte.")])

C[13] = dict(
intro="Treze anos de casados são as <b>Bodas de Linho</b> (ou de renda). É a boda da simplicidade elegante.",
sig=["O linho é um tecido natural, antigo, fresco e nobre. Não precisa de enfeite pra ser bonito. Aos treze anos, o casal já não precisa provar nada a ninguém: a relação é natural, verdadeira, sem esforço pra parecer perfeita.",
"E linho amassa — faz parte do charme dele. Um casamento de treze anos também tem as suas dobras, e está tudo bem."],
origem="O linho é uma das fibras mais antigas usadas pela humanidade; os egípcios já o teciam. Nas listas brasileiras aparece aos 13 anos, com a renda como alternativa — dois tecidos que exigem trabalho manual e paciência.",
presentes=[("Toalha de mesa de linho","Pros almoços de família."),
("Camisa ou vestido de linho","Pro verão, pra uma viagem."),
("Jogo americano bordado","Com as iniciais do casal."),
("Peça de renda artesanal","Renda de bilro ou renascença, arte brasileira."),
("Viagem pra praia","O linho pede sol."),
("Quadro das Bodas de Linho","Com os nomes, a data e os mais de 4.700 dias juntos.")],
frases=[("Pro amor","Treze anos de um amor simples, verdadeiro e bonito como linho. Feliz Bodas de Linho."),
("Pro casal","Que a vida de vocês siga leve e natural. Parabéns pelos 13 anos de casados!"),
("Legenda curta","13 anos: menos pose, mais verdade. Bodas de Linho 🤍"),
("Pro cartão","Com você, eu não preciso fingir nada. Isso é tudo."),
("Pro número 13","Treze anos e a única sorte que eu preciso é você.")],
comemorar=["Almoço ao ar livre com toalha de linho e comida simples.","Viagem pra uma praia tranquila.","Visitar uma cidade de artesanato de renda, como no Nordeste.","Um ensaio de fotos com roupas claras e naturais."],
faq=[("13 anos de casados são bodas de quê?","Bodas de Linho. Algumas listas trazem bodas de renda."),
("Presente de bodas de linho?","Toalha de mesa, roupa de linho, peça de renda artesanal ou um quadro personalizado.")])

C[14] = dict(
intro="Catorze anos de casados são as <b>Bodas de Marfim</b>. É a boda do amor que ficou precioso.",
sig=["O marfim sempre foi um material raro e valioso, e é por isso que ele simboliza um casamento de catorze anos: algo que ganhou valor com o tempo e que não se encontra em qualquer lugar.",
"A cor também conta: o branco levemente amarelado lembra coisas antigas e bem cuidadas, como a renda do vestido de noiva da avó."],
origem="O marfim entrou nas listas de bodas numa época em que era comum em joias e objetos. Hoje o comércio de marfim é proibido pra proteger os elefantes, então a boda se comemora pelo símbolo e pela cor — com presentes em tom marfim, pérola, osso ou madrepérola.",
presentes=[("Joia em tom marfim ou madrepérola","Colar, brinco ou abotoadura."),
("Porcelana branca","Um jogo de chá ou uma peça decorativa."),
("Velas e aromas em tom marfim","Pra uma noite especial."),
("Roupa de cama branca de boa qualidade","Clássico elegante."),
("Doação em nome do casal","Pra uma ONG de proteção aos elefantes — um presente com consciência."),
("Quadro das Bodas de Marfim","No estilo Clássico, que já é em tom marfim.")],
frases=[("Pro amor","Catorze anos e você é a coisa mais rara que eu tenho. Feliz Bodas de Marfim."),
("Pro casal","Que o amor de vocês continue raro e precioso. Parabéns pelos 14 anos!"),
("Legenda curta","14 anos de um amor raro. Bodas de Marfim 🤍"),
("Pro cartão","O tempo só deixou a gente mais valioso um pro outro."),
("Pros pais","Catorze anos de um casamento que a gente admira. Parabéns!")],
comemorar=["Jantar à luz de velas em tons claros.","Um ensaio de fotos com a roupa do casamento (ou parecida).","Um passeio num lugar histórico da cidade.","Uma doação ou um voluntariado juntos, em vez do presente tradicional."],
faq=[("14 anos de casados são bodas de quê?","Bodas de Marfim."),
("Dá pra dar marfim de presente?","Não: o comércio de marfim é proibido. Comemore com o simbolismo e a cor — madrepérola, porcelana branca ou objetos em tom marfim.")])

C[15] = dict(
intro="Quinze anos de casados são as <b>Bodas de Cristal</b>. É uma das bodas mais comemoradas, depois das de prata e ouro.",
sig=["O cristal é transparente e brilha quando a luz passa por ele. Quinze anos depois, o casal já não tem segredos: é uma relação de confiança, clara, em que um enxerga o outro por inteiro.",
"E cristal é duro, mas não pode cair. A boda fala de um amor sólido que ainda merece cuidado — nada de dar a relação como garantida."],
origem="O cristal aos 15 anos é tradição forte no Brasil, em Portugal e nos Estados Unidos. Por ser um marco redondo e bonito, muitos casais fazem festa ou renovam os votos nas Bodas de Cristal.",
presentes=[("Taças de cristal gravadas","Pra brindar hoje e nas próximas bodas."),
("Joia com cristal","Colar, brinco ou pulseira com pedra transparente."),
("Luminária ou castiçal de cristal","Luz e transparência na casa."),
("Garrafa de espumante e duas taças","Pra um brinde a dois."),
("Viagem de 15 anos","Uma segunda lua de mel."),
("Quadro das Bodas de Cristal","Com os nomes e os mais de 5.400 dias juntos.")],
frases=[("Pro amor","Quinze anos de um amor transparente e brilhante. Feliz Bodas de Cristal, meu amor."),
("Pro casal","Que o amor de vocês continue claro e brilhando como cristal. Parabéns pelos 15 anos!"),
("Legenda curta","15 anos de casados, nada a esconder. Bodas de Cristal 🥂"),
("Pro cartão","Com você, tudo é claro: eu sei onde estou, com quem estou e por quê."),
("Pros pais","Quinze anos de casamento e um exemplo de parceria que a gente leva pra vida. Parabéns, pai e mãe!")],
comemorar=["Renovação de votos com os padrinhos do casamento.","Festa com brinde de espumante em taças de cristal.","Viagem a dois pra um lugar que sempre quiseram conhecer.","Uma sessão de fotos da família inteira."],
faq=[("15 anos de casados são bodas de quê?","Bodas de Cristal, uma das bodas mais festejadas."),
("O que dar de presente nas bodas de cristal para os pais?","Taças de cristal gravadas, uma viagem, uma festa surpresa ou um quadro das Bodas de Cristal com os nomes e a data.")])

C[16] = dict(
intro="Dezesseis anos de casados são as <b>Bodas de Safira</b> (em algumas listas, de turmalina). É a primeira pedra preciosa da lista.",
sig=["A safira é uma pedra azul, muito dura, associada à lealdade e à sabedoria. Aos dezesseis anos, o casal tem as duas coisas: a fidelidade de quem escolheu ficar e a sabedoria de quem aprendeu a conviver.",
"O azul também é a cor da calma. Dezesseis anos depois, a relação é porto seguro."],
origem="A safira é tradicionalmente ligada a compromissos — a própria princesa Diana ficou noiva com um anel de safira. Nas listas brasileiras ela aparece aos 16 anos; algumas trazem a turmalina, pedra muito comum no Brasil.",
presentes=[("Joia com safira ou pedra azul","Anel, brinco ou pingente."),
("Turmalina brasileira","Pra quem segue a outra tradição — o Brasil é um dos maiores produtores."),
("Viagem pro mar","O azul da boda pede praia."),
("Jantar com toques de azul","Flores, velas e louça azul."),
("Relógio ou abotoadura com detalhe azul","Pra ele."),
("Quadro das Bodas de Safira","No estilo Noite de gala, que combina com o azul.")],
frases=[("Pro amor","Dezesseis anos de lealdade, parceria e calma. Você é a minha safira. Feliz Bodas de Safira."),
("Pro casal","Que o amor de vocês continue firme e leal como safira. Parabéns pelos 16 anos!"),
("Legenda curta","16 anos de casados, azul de calma. Bodas de Safira 💙"),
("Pro cartão","Em dezesseis anos, você nunca me deixou sozinho. Obrigado."),
("Pros tios","Dezesseis anos de um casamento bonito de ver. Parabéns pelas Bodas de Safira!")],
comemorar=["Viagem pra praia ou pra um lago.","Jantar num restaurante com vista pro mar.","Passeio de barco.","Um presente com pedra azul entregue num lugar especial pro casal."],
faq=[("16 anos de casados são bodas de quê?","Bodas de Safira. Algumas listas trazem bodas de turmalina."),
("O que simboliza a safira?","Lealdade, fidelidade e sabedoria. É uma das pedras mais duras que existem, depois do diamante.")])

C[17] = dict(
intro="Dezessete anos de casados são as <b>Bodas de Rosa</b>. É a boda do romance que não acabou.",
sig=["A rosa é a flor do amor em quase todas as culturas. Aos dezessete anos ela volta pra lembrar que, depois de tanto tempo, ainda cabe romance: flores sem motivo, bilhete no espelho, dança na cozinha.",
"Rosa também tem espinhos, e o casal já sabe disso. O que importa é que continua florescendo."],
origem="A rosa aparece aos 17 anos nas listas brasileiras. É uma boda menos conhecida, o que torna a surpresa ainda maior: pouca gente espera uma comemoração nessa data.",
presentes=[("17 rosas","Uma pra cada ano. Clássico que emociona."),
("Roseira pra plantar","Uma rosa que vai durar anos."),
("Perfume de rosas","Um cheiro pra lembrar da data."),
("Joia com rosa","Pingente, anel ou brinco em formato de rosa."),
("Rosa eterna em cúpula","A rosa preservada que dura anos."),
("Quadro das Bodas de Rosa","No estilo Floral, com os nomes e a data.")],
frases=[("Pro amor","Dezessete anos e eu ainda quero te dar flores sem motivo. Feliz Bodas de Rosa."),
("Pro casal","Que o amor de vocês continue florescendo como uma roseira. Parabéns pelos 17 anos!"),
("Legenda curta","17 anos, 17 rosas e o mesmo romance. Bodas de Rosa 🌹"),
("Pro cartão","Nem os espinhos tiraram a beleza do que a gente plantou."),
("Pros pais","Dezessete anos e o romance de vocês continua inspirando a gente. Parabéns!")],
comemorar=["Um jantar romântico com pétalas de rosa na mesa.","Visitar um roseiral ou um jardim de rosas.","Uma noite de dança, mesmo que seja na sala.","Plantar uma roseira juntos."],
faq=[("17 anos de casados são bodas de quê?","Bodas de Rosa."),
("Quantas rosas dar nas bodas de rosa?","Dezessete, uma por ano de casamento, é a tradição mais bonita.")])

C[18] = dict(
intro="Dezoito anos de casados são as <b>Bodas de Turquesa</b>. É a boda da proteção e da sorte.",
sig=["A turquesa é uma pedra azul-esverdeada usada há milhares de anos como amuleto de proteção. Aos dezoito anos — a \"maioridade\" do casamento —, ela simboliza um amor que cuida e protege.",
"Muitas culturas acreditam que a turquesa muda de cor pra avisar o dono de um perigo. É um bom símbolo pra um casal que já conhece tão bem um ao outro que percebe tudo no olhar."],
origem="A turquesa aparece aos 18 anos nas listas brasileiras. É uma pedra ligada aos povos indígenas das Américas, ao Egito antigo e à Pérsia, sempre como símbolo de proteção e boa sorte.",
presentes=[("Joia com turquesa","Pulseira, colar ou anel."),
("Objetos de decoração cor turquesa","Almofadas, vasos, uma luminária."),
("Viagem pra um lugar de água turquesa","Caribe brasileiro: Maragogi, Jericoacoara, Fernando de Noronha."),
("Amuleto do casal","Um chaveiro ou pingente de proteção pra cada um."),
("Festa da \"maioridade\"","Com os amigos de sempre."),
("Quadro das Bodas de Turquesa","Com os nomes e os mais de 6.500 dias juntos.")],
frases=[("Pro amor","Dezoito anos: nosso casamento chegou à maioridade. E eu continuo querendo te proteger de tudo. Feliz Bodas de Turquesa."),
("Pro casal","Que nunca falte sorte e proteção pra vocês. Parabéns pelos 18 anos!"),
("Legenda curta","18 anos: maioridade do amor. Bodas de Turquesa 💎"),
("Pro cartão","Você é o meu amuleto de sorte desde o primeiro dia."),
("Divertida","18 anos de casados: agora nosso casamento pode tirar carteira de motorista.")],
comemorar=["Uma viagem pra praia de água clara.","Festa temática de \"maioridade\" do casamento.","Um jantar com os padrinhos.","Um passeio de mergulho ou snorkel."],
faq=[("18 anos de casados são bodas de quê?","Bodas de Turquesa."),
("O que significa a turquesa nas bodas?","Proteção, sorte e cuidado. É uma das pedras de amuleto mais antigas do mundo.")])

C[19] = dict(
intro="Dezenove anos de casados são as <b>Bodas de Cretone</b> (em algumas listas, de água-marinha). É a última boda antes dos 20 anos.",
sig=["O cretone é um tecido de algodão grosso, forte e estampado, muito usado em cortinas e estofados. Aos dezenove anos, o casamento é assim: resistente, colorido e parte da decoração da vida — está em cada canto da casa.",
"É uma boda pouco conhecida, mas carrega uma ideia bonita: a de uma relação que aguenta o uso diário sem perder a cor."],
origem="O cretone é tradição das listas brasileiras e portuguesas. A água-marinha, pedra azul-clara muito brasileira, aparece em listas alternativas para o mesmo ano.",
presentes=[("Almofadas ou cortina estampadas","Pra renovar um canto da casa."),
("Joia com água-marinha","Pedra brasileira, pra quem segue a outra tradição."),
("Reforma de uma poltrona antiga","Com tecido novo e resistente."),
("Bolsa ou sacola de tecido estampado","Útil e colorida."),
("Um fim de semana fora","Pra descansar antes da grande festa dos 20."),
("Quadro das Bodas de Cretone","Com os nomes e os mais de 6.900 dias juntos.")],
frases=[("Pro amor","Dezenove anos e a nossa vida continua colorida. Feliz Bodas de Cretone."),
("Pro casal","Que o amor de vocês siga forte e colorido. Parabéns pelos 19 anos!"),
("Legenda curta","19 anos de casados. Ano que vem é porcelana! 🧵"),
("Pro cartão","A gente estampou a casa inteira com a nossa história."),
("Pra quem já está planejando os 20","Um ano pra porcelana. Mas hoje é dia de comemorar o que a gente já é.")],
comemorar=["Um jantar a dois pra começar a planejar a festa dos 20 anos.","Renovar a decoração da sala juntos.","Uma viagem curta pra relaxar.","Um álbum com uma foto de cada ano de casamento."],
faq=[("19 anos de casados são bodas de quê?","Bodas de Cretone. Algumas listas trazem bodas de água-marinha."),
("O que é cretone?","É um tecido de algodão grosso e resistente, geralmente estampado, usado em cortinas e estofados.")])

C[20] = dict(
intro="Vinte anos de casados são as <b>Bodas de Porcelana</b>. Duas décadas juntos — uma das bodas mais bonitas de comemorar.",
sig=["A porcelana é feita de uma argila especial queimada em temperatura altíssima. O resultado é uma peça fina, bonita, resistente ao calor e muito valiosa. Vinte anos de casamento são assim: passaram pelo fogo e ficaram refinados.",
"A porcelana também é a louça das ocasiões especiais, guardada com carinho pras festas da família. Um casamento de vinte anos é essa louça boa: usada com cuidado, passada de geração em geração."],
origem="A porcelana foi inventada na China há mais de mil anos e, por séculos, foi mais valiosa que ouro na Europa. Por isso marca os 20 anos nas listas do Brasil, de Portugal e de vários países. É uma boda que costuma ter festa, e muitos filhos organizam a surpresa pros pais.",
presentes=[("Jogo de chá ou de jantar de porcelana","O presente clássico, pra usar nas próximas festas."),
("Peça de porcelana decorativa","Um vaso ou uma estatueta."),
("Viagem das duas décadas","Pra um lugar novo, ou pra refazer a lua de mel."),
("Festa surpresa organizada pelos filhos","Com fotos das duas décadas."),
("Joia com o número 20 ou a data","Pra guardar pra sempre."),
("Quadro das Bodas de Porcelana","Com os nomes, a data e os 7.305 dias juntos — o presente que os filhos mais dão.")],
frases=[("Pro amor","Vinte anos passando pelo fogo e ficando mais bonitos. Feliz Bodas de Porcelana, meu amor."),
("Pros pais","Vinte anos do casamento de vocês e a gente cresceu aprendendo o que é amor de verdade. Parabéns, pai e mãe!"),
("Legenda curta","20 anos, 7.305 dias e a louça boa na mesa. Bodas de Porcelana 🫖"),
("Pro cartão","Duas décadas e você continua sendo a melhor decisão que eu já tomei."),
("Pro casal amigo","Vinte anos juntos é pra poucos. Que venham os de prata! Parabéns pelas Bodas de Porcelana.")],
comemorar=["Um chá da tarde ou um jantar servido na porcelana da família.","Festa surpresa com fotos das duas décadas no telão.","Renovação de votos com os filhos como padrinhos.","Uma viagem pra um lugar que vocês sempre quiseram conhecer."],
faq=[("20 anos de casados são bodas de quê?","Bodas de Porcelana."),
("O que dar de presente de bodas de porcelana para os pais?","Um jogo de porcelana, uma viagem, uma festa surpresa ou um quadro das Bodas de Porcelana com os nomes e a data.")])
