# -*- coding: utf-8 -*-
# Conteúdo único por boda (25 a 75 anos).
C = {}

C[25] = dict(
intro="Vinte e cinco anos de casados são as <b>Bodas de Prata</b>. Um quarto de século juntos — a boda mais famosa depois das de ouro.",
sig=["A prata é um metal nobre, que brilha e não perde o valor. Mas tem um detalhe: escurece se ficar esquecida e volta a brilhar com um pouco de cuidado. É exatamente o que 25 anos de casamento ensinam — o amor precisa de atenção pra continuar brilhando.",
"Vinte e cinco anos também é, muitas vezes, a fase em que os filhos estão crescidos e o casal volta a olhar um pro outro. Uma nova etapa começa."],
origem="As bodas de prata vêm da Europa medieval, especialmente da Alemanha, onde o marido dava à esposa uma coroa de prata aos 25 anos de casamento (e de ouro aos 50). É a tradição mais antiga de todas as bodas, e até hoje é a que mais tem festa, missa e renovação de votos.",
presentes=[("Joia de prata","Anel, pulseira ou colar gravado com as duas datas."),
("Alianças novas de prata","Pra usar junto com as de casamento."),
("Viagem das Bodas de Prata","A segunda lua de mel clássica."),
("Festa ou missa de renovação de votos","Com os padrinhos, se possível."),
("Porta-retrato de prata","Com a foto do casamento ao lado de uma foto atual."),
("Quadro das Bodas de Prata","Com os nomes, a data e os mais de 9.100 dias juntos — o presente preferido dos filhos.")],
frases=[("Pro amor","Vinte e cinco anos e você continua sendo a minha escolha de todo dia. Feliz Bodas de Prata."),
("Pros pais","Um quarto de século de amor, de parceria e de família. Obrigado por nos mostrarem como se faz. Parabéns pelas Bodas de Prata, pai e mãe!"),
("Legenda curta","25 anos juntos. Brilho de prata. 🥈"),
("Pro cartão","A gente polia a prata um do outro todo dia, sem perceber. Olha como brilha."),
("Pros tios ou amigos","Vinte e cinco anos de casamento é inspiração. Que venham as de ouro! Parabéns!")],
comemorar=["Renovação de votos com festa pra família e os amigos.","Refazer a lua de mel no mesmo destino, 25 anos depois.","Uma festa surpresa organizada pelos filhos, com fotos de 1 a 25 anos.","Recriar a foto do casamento, no mesmo lugar e na mesma pose."],
faq=[("25 anos de casados são bodas de quê?","Bodas de Prata."),
("O que dar de presente de bodas de prata para os pais?","Joia de prata com as datas, uma viagem, uma festa surpresa ou um quadro das Bodas de Prata com os nomes e os dias juntos.")])

C[30] = dict(
intro="Trinta anos de casados são as <b>Bodas de Pérola</b>. Três décadas de uma história construída camada por camada.",
sig=["A pérola nasce quando um grão de areia entra na ostra. Pra se proteger, ela cobre o grão com camadas e camadas de nácar, durante anos, até formar algo precioso. Trinta anos de casamento são assim: dos incômodos e dos grãos de areia do dia a dia, o casal fez uma coisa linda.",
"É também uma joia que não precisa ser lapidada: ela já nasce pronta. Como um amor de trinta anos, que já não precisa de retoques."],
origem="A pérola é associada aos 30 anos nas listas do Brasil, de Portugal e dos Estados Unidos. É uma das joias mais antigas usadas pela humanidade, símbolo de pureza e sabedoria em várias culturas.",
presentes=[("Colar ou brinco de pérola","O presente clássico, pra usar nas festas da família."),
("Abotoadura com pérola","Pra ele."),
("Viagem pro litoral","Pra ver o mar de onde vêm as pérolas."),
("Livro da família","Com fotos e depoimentos dos filhos e netos."),
("Jantar com frutos do mar","Em homenagem à ostra."),
("Quadro das Bodas de Pérola","Com os nomes, a data e os mais de 10.900 dias juntos.")],
frases=[("Pro amor","Trinta anos transformando grãos de areia em pérola. Feliz Bodas de Pérola, meu amor."),
("Pros pais","Três décadas de casamento e uma família inteira que nasceu desse amor. Parabéns pelas Bodas de Pérola!"),
("Legenda curta","30 anos, camada por camada. Bodas de Pérola 🦪"),
("Pro cartão","Obrigado por transformar cada dia difícil em algo precioso."),
("Pros avós","Trinta anos de casamento de vocês e a gente só tem o que agradecer. Parabéns, vovô e vovó!")],
comemorar=["Um almoço de família com todos os filhos e netos.","Uma viagem pro litoral, com jantar de frutos do mar.","Um livro de recados da família, com mensagens de cada um.","Renovar os votos na mesma igreja do casamento."],
faq=[("30 anos de casados são bodas de quê?","Bodas de Pérola."),
("O que dar de presente de bodas de pérola?","Joias com pérola, uma viagem pro litoral, um livro com recados da família ou um quadro das Bodas de Pérola.")])

C[35] = dict(
intro="Trinta e cinco anos de casados são as <b>Bodas de Coral</b>. É a boda do amor que virou abrigo pra muita vida.",
sig=["O coral cresce devagar, poucos centímetros por ano, no fundo do mar. Com o tempo, vira um recife onde vivem milhares de peixes e plantas. Trinta e cinco anos de casamento também criam um ecossistema inteiro: filhos, netos, amigos, uma família que se abriga ali.",
"A cor coral, entre o rosa e o laranja, é quente e alegre — como uma casa sempre cheia."],
origem="O coral aparece aos 35 anos em várias listas do Ocidente, às vezes junto com o jade. É uma boda menos lembrada que as de prata e ouro, o que torna uma comemoração ainda mais especial.",
presentes=[("Joia com coral ou na cor coral","Hoje o coral natural é protegido, prefira pedras ou esmalte na cor."),
("Viagem pra um lugar de recifes","Porto de Galinhas, Maragogi, Abrolhos."),
("Almoço em família","Com todas as gerações que nasceram desse casamento."),
("Flores em tons de coral","Rosas, gérberas ou peônias salmão."),
("Árvore genealógica ilustrada","Com o casal na raiz."),
("Quadro das Bodas de Coral","No estilo Floral, com os nomes e os mais de 12.700 dias juntos.")],
frases=[("Pro amor","Trinta e cinco anos construindo, devagar, um lugar onde a família inteira cabe. Feliz Bodas de Coral."),
("Pros pais","Vocês são o recife onde a nossa família cresceu. Parabéns pelos 35 anos de casados!"),
("Legenda curta","35 anos de casados e uma casa cheia de vida. Bodas de Coral 🪸"),
("Pro cartão","Tudo de bom que a gente tem cresceu em volta do nosso amor."),
("Pros avós","Trinta e cinco anos e três gerações. Obrigado por tudo, vovô e vovó!")],
comemorar=["Um almoço grande com todas as gerações da família.","Uma viagem pra ver os recifes de coral.","Uma foto da família inteira pra pendurar ao lado da foto do casamento.","Um livro de receitas da família, com os pratos preferidos do casal."],
faq=[("35 anos de casados são bodas de quê?","Bodas de Coral."),
("Pode dar coral de presente?","O coral natural é protegido por lei em muitos lugares. Prefira objetos na cor coral ou joias com pedras que imitam o tom.")])

C[40] = dict(
intro="Quarenta anos de casados são as <b>Bodas de Esmeralda</b> (algumas listas trazem rubi). Quatro décadas juntos.",
sig=["A esmeralda é a pedra verde mais preciosa do mundo, e o verde é a cor da esperança. Depois de quarenta anos, o casal ainda faz planos, ainda sonha junto, ainda tem vontade de seguir — é isso que a boda celebra.",
"A esmeralda também é famosa pelas \"inclusões\", pequenas marcas internas que os joalheiros chamam de jardim. Um casamento de quarenta anos também tem o seu jardim de marcas, e é justamente isso que o torna único."],
origem="O Brasil é um dos maiores produtores de esmeraldas do mundo, o que dá à boda um sabor especial por aqui. Nos Estados Unidos e na Inglaterra, os 40 anos costumam ser as bodas de rubi; no Brasil, a esmeralda é a mais usada, e o rubi fica pros 45.",
presentes=[("Joia com esmeralda","Pedra brasileira, pra durar mais quarenta anos."),
("Viagem das quatro décadas","Um cruzeiro, uma viagem pra Europa ou pro lugar dos sonhos."),
("Festa com a família e os amigos antigos","Chamando quem esteve no casamento."),
("Um jardim ou uma árvore","Verde da esperança, plantado juntos."),
("Álbum das quatro décadas","Uma foto marcante de cada ano."),
("Quadro das Bodas de Esmeralda","Com os nomes e os mais de 14.600 dias juntos.")],
frases=[("Pro amor","Quarenta anos e eu ainda tenho esperança em tudo o que a gente vai viver. Feliz Bodas de Esmeralda."),
("Pros pais","Quatro décadas de amor, de luta e de família. Vocês são o nosso maior exemplo. Parabéns pelas Bodas de Esmeralda!"),
("Legenda curta","40 anos de casados e ainda cheios de planos. Bodas de Esmeralda 💚"),
("Pro cartão","Quarenta anos depois, eu ainda quero envelhecer do seu lado."),
("Pros avós","Quarenta anos de um amor que deu origem a todos nós. Parabéns, vovô e vovó!")],
comemorar=["Uma festa com os padrinhos e os amigos do casamento.","Uma viagem de sonho, de preferência dada pelos filhos.","Renovação de votos com os netos levando as alianças.","Uma exposição de fotos das quatro décadas na festa."],
faq=[("40 anos de casados são bodas de quê?","No Brasil, Bodas de Esmeralda. Em algumas listas estrangeiras, os 40 anos são de rubi."),
("O que dar nas bodas de esmeralda para os pais?","Uma joia com esmeralda, uma viagem, uma festa com os amigos antigos ou um quadro das Bodas de Esmeralda com os nomes e a data.")])

C[45] = dict(
intro="Quarenta e cinco anos de casados são as <b>Bodas de Rubi</b>. É a boda da paixão que não apagou.",
sig=["O rubi é a pedra vermelha mais valiosa, e o vermelho é a cor da paixão, do fogo e do coração. Depois de quarenta e cinco anos, celebrar com um rubi é dizer que o amor continua vivo — não só como companheirismo, mas como paixão.",
"O rubi também é duríssimo, perde só pro diamante. Um amor de quarenta e cinco anos também já provou que aguenta quase tudo."],
origem="Nas listas brasileiras, o rubi marca os 45 anos (em algumas estrangeiras, os 40). Antigamente se acreditava que o rubi guardava uma chama eterna dentro dele — símbolo perfeito pra um casamento tão longo.",
presentes=[("Joia com rubi ou pedra vermelha","Anel, pingente ou abotoadura."),
("Rosas vermelhas","Quarenta e cinco, se couber no vaso."),
("Jantar romântico com vinho tinto","Tudo no tom da boda."),
("Viagem a dois","Sem netos, sem compromisso."),
("Fotolivro da história do casal","Do namoro até hoje."),
("Quadro das Bodas de Rubi","Com os nomes e os mais de 16.400 dias juntos.")],
frases=[("Pro amor","Quarenta e cinco anos e o meu coração ainda acelera quando você chega. Feliz Bodas de Rubi."),
("Pros pais","Quarenta e cinco anos de amor que a gente vê em cada gesto de vocês. Parabéns pelas Bodas de Rubi!"),
("Legenda curta","45 anos de casados. A chama continua acesa. Bodas de Rubi ❤️"),
("Pro cartão","A paixão mudou de jeito, mas nunca foi embora."),
("Pros avós","Quarenta e cinco anos de um amor que é a raiz da nossa família. Parabéns!")],
comemorar=["Um jantar romântico, com a mesma música da primeira dança.","Uma viagem a dois organizada pelos filhos.","Festa com decoração vermelha e as fotos do casamento.","Um baile com as músicas da época do namoro."],
faq=[("45 anos de casados são bodas de quê?","Bodas de Rubi (no Brasil). Algumas listas estrangeiras usam o rubi para os 40 anos."),
("O que simboliza o rubi nas bodas?","Paixão, coragem e um amor que continua aceso depois de muito tempo.")])

C[50] = dict(
intro="Cinquenta anos de casados são as <b>Bodas de Ouro</b>. Meio século juntos — a boda mais celebrada de todas.",
sig=["O ouro é o metal mais nobre: não enferruja, não escurece, não perde o valor. Cinquenta anos de casamento são exatamente isso — uma união que atravessou tudo e continua valiosa.",
"É também uma festa de gerações. Nas Bodas de Ouro estão filhos, netos, às vezes bisnetos: todo mundo que existe por causa daquele \"sim\" dito cinquenta anos antes."],
origem="Junto com a de prata, é a boda mais antiga: na Alemanha medieval, o casal que chegava aos 50 anos ganhava uma coroa de ouro. No Brasil, as Bodas de Ouro costumam ter missa, renovação de votos e festa, quase sempre organizada pelos filhos.",
presentes=[("Alianças de ouro novas ou regravadas","Com as datas de 50 anos atrás e de hoje."),
("Festa ou missa organizada pelos filhos","Com os amigos que ainda estão aqui."),
("Livro de recados da família","Mensagens de filhos, netos e amigos, pra reler sempre."),
("Viagem ou cruzeiro","O presente dos sonhos, dado por todos os filhos juntos."),
("Joia de ouro","Com o número 50 ou as iniciais."),
("Quadro das Bodas de Ouro","Com os nomes, a data e os mais de 18.000 dias juntos — lindo no estilo Noite de gala.")],
frases=[("Pro amor","Cinquenta anos depois, eu diria sim de novo, sem pensar. Feliz Bodas de Ouro, meu amor."),
("Pros pais","Meio século de amor que deu origem a tudo o que a gente é. Obrigado, pai e mãe. Parabéns pelas Bodas de Ouro!"),
("Pros avós","Cinquenta anos de casamento e uma família inteira pra provar que valeu a pena. Parabéns, vovô e vovó!"),
("Legenda curta","50 anos de casados. Ouro puro. 🥇"),
("Pro convite ou telão","Há 50 anos eles disseram sim. Hoje, a família inteira diz obrigado.")],
comemorar=["Missa ou cerimônia de renovação de votos, com os netos como pajens.","Festa com fotos das cinco décadas e as músicas da época do casamento.","Um livro de recados, com mensagens de cada filho, neto e amigo.","Recriar a foto do casamento com o mesmo casal, 50 anos depois."],
faq=[("50 anos de casados são bodas de quê?","Bodas de Ouro, a boda mais celebrada."),
("O que dar de presente nas bodas de ouro dos pais?","Uma festa ou missa, um livro de recados da família, uma viagem, alianças novas ou um quadro das Bodas de Ouro com os nomes e os dias juntos.")])

C[55] = dict(
intro="Cinquenta e cinco anos de casados são as <b>Bodas de Ametista</b>. É a boda da serenidade.",
sig=["A ametista é uma pedra roxa associada à calma, à sabedoria e ao equilíbrio. Depois de cinquenta e cinco anos, o casal tem uma paz que só o tempo dá: sabe o que importa, não briga por pouco, entende o silêncio do outro.",
"Os gregos acreditavam que a ametista protegia contra os excessos. É um símbolo bonito pra um amor maduro, que encontrou a medida certa."],
origem="A ametista marca os 55 anos nas listas brasileiras. O Brasil, especialmente o Rio Grande do Sul, é um dos maiores produtores de ametista do mundo — as famosas geodos roxas saem de lá.",
presentes=[("Joia com ametista","Pedra brasileira, em anel, colar ou brinco."),
("Geodo de ametista","Peça decorativa linda pra casa."),
("Flores em tons de lilás","Lavanda, orquídeas, violetas."),
("Um dia tranquilo com a família","Almoço sem pressa, com todos juntos."),
("Álbum de memórias","Com fotos antigas digitalizadas e restauradas."),
("Quadro das Bodas de Ametista","Com os nomes e os mais de 20.000 dias juntos.")],
frases=[("Pro amor","Cinquenta e cinco anos e a sua companhia continua sendo a minha paz. Feliz Bodas de Ametista."),
("Pros pais","Cinquenta e cinco anos de um amor sereno e forte. Parabéns pelas Bodas de Ametista!"),
("Legenda curta","55 anos de casados, em paz. Bodas de Ametista 💜"),
("Pro cartão","Com você, até o silêncio é boa companhia."),
("Pros avós","Cinquenta e cinco anos e a mesma calma de sempre. Amamos vocês, vovô e vovó!")],
comemorar=["Um almoço de família sem pressa, na casa do casal.","Restaurar as fotos antigas do casamento e montar um álbum.","Uma viagem tranquila pra serra, com os filhos.","Uma missa ou oração em família."],
faq=[("55 anos de casados são bodas de quê?","Bodas de Ametista."),
("O que simboliza a ametista?","Serenidade, sabedoria e equilíbrio.")])

C[60] = dict(
intro="Sessenta anos de casados são as <b>Bodas de Diamante</b>. Seis décadas juntos — um amor indestrutível.",
sig=["O diamante é o material natural mais duro que existe e se forma ao longo de milhões de anos, sob uma pressão enorme. Sessenta anos de casamento também passaram por muita pressão e saíram brilhando.",
"O nome vem do grego \"adamas\", que quer dizer invencível. Poucos casais chegam aqui, e é por isso que as Bodas de Diamante são tão especiais."],
origem="As bodas de diamante marcam os 60 anos no Brasil e em Portugal (em alguns países são os 75). Ficaram famosas quando a rainha Vitória, da Inglaterra, comemorou o \"jubileu de diamante\" do seu reinado. Hoje, sessenta anos de casamento costumam reunir quatro gerações.",
presentes=[("Joia com diamante ou brilhante","Um anel de eternidade é o presente clássico."),
("Festa com quatro gerações","Filhos, netos e bisnetos."),
("Livro de recados e fotos da família","Pra reler com calma."),
("Uma homenagem na igreja ou na comunidade","Onde o casal tem amigos de décadas."),
("Vídeo com depoimentos da família","Pra passar no telão da festa."),
("Quadro das Bodas de Diamante","Com os nomes e os mais de 21.900 dias juntos.")],
frases=[("Pro amor","Sessenta anos e nada conseguiu apagar o nosso brilho. Feliz Bodas de Diamante."),
("Pros avós","Sessenta anos de amor, quatro gerações e uma história que a gente vai contar pra sempre. Parabéns, vovô e vovó!"),
("Pros pais","Seis décadas de casamento. Obrigado por serem a nossa base. Parabéns pelas Bodas de Diamante!"),
("Legenda curta","60 anos de casados. Invencíveis. Bodas de Diamante 💎"),
("Pro telão","Sessenta anos atrás eles começaram uma família. Hoje, ela lota este salão.")],
comemorar=["Uma festa com as quatro gerações da família.","Uma missa ou cerimônia de bênção das alianças.","Um vídeo com depoimentos de filhos, netos e bisnetos.","Uma foto oficial da família inteira."],
faq=[("60 anos de casados são bodas de quê?","Bodas de Diamante."),
("O que dar de presente nas bodas de diamante dos avós?","Uma festa com a família, um vídeo com depoimentos, um livro de recados ou um quadro das Bodas de Diamante com os nomes e a data.")])

C[65] = dict(
intro="Sessenta e cinco anos de casados são as <b>Bodas de Platina</b>. Um metal mais raro que o ouro, pra uma união mais rara ainda.",
sig=["A platina é um dos metais mais raros e resistentes do planeta — mais rara que o ouro e quase impossível de desgastar. Chegar aos sessenta e cinco anos de casamento é para pouquíssimos, e a boda reconhece isso.",
"A platina também não muda de cor com o tempo. Como um amor que, depois de tantas décadas, continua do mesmo jeito."],
origem="Nas listas brasileiras a platina aparece aos 65 anos (em algumas, a safira azul). É uma das bodas mais raras de se comemorar, e muitas famílias aproveitam pra fazer uma homenagem pública ao casal.",
presentes=[("Joia de platina ou de metal branco","Com as duas datas gravadas."),
("Homenagem da família","Um almoço com discursos dos filhos e netos."),
("Um retrato pintado do casal","A partir de uma foto antiga ou atual."),
("Fotos antigas restauradas","Numa caixa ou num álbum."),
("Um passeio especial","Ao lugar onde o casal se conheceu."),
("Quadro das Bodas de Platina","Com os nomes e os mais de 23.700 dias juntos.")],
frases=[("Pro amor","Sessenta e cinco anos e eu ainda procuro a sua mão quando acordo. Feliz Bodas de Platina."),
("Pros avós","Sessenta e cinco anos de um amor raro como platina. Obrigado por tudo, vovô e vovó!"),
("Legenda curta","65 anos de casados. Coisa rara. Bodas de Platina 🤍"),
("Pro cartão","Muita coisa mudou no mundo em 65 anos. O nosso amor, não."),
("Pros pais","Sessenta e cinco anos de exemplo. Parabéns pelas Bodas de Platina!")],
comemorar=["Um almoço de família com discursos de cada geração.","Uma visita ao lugar onde tudo começou.","Um retrato do casal pra ficar na sala.","Uma bênção das alianças na igreja do casamento."],
faq=[("65 anos de casados são bodas de quê?","Bodas de Platina."),
("A platina é mais valiosa que o ouro?","Em geral é mais rara e mais resistente, por isso simboliza uma união tão longa e rara.")])

C[70] = dict(
intro="Setenta anos de casados são as <b>Bodas de Vinho</b>. Como o vinho, o amor melhorou com o tempo.",
sig=["O vinho bom precisa de anos pra ficar pronto: repousa, amadurece e ganha sabor. Setenta anos de casamento são um vinho raríssimo, desses que a família guarda pra ocasiões muito especiais.",
"O vinho também é bebida de celebração e de mesa compartilhada. Não há símbolo melhor pra uma família inteira reunida em volta do casal."],
origem="As bodas de vinho marcam os 70 anos nas listas brasileiras. Em algumas listas estrangeiras, os 70 anos são de platina. É uma boda rara, e cada comemoração vira história na família.",
presentes=[("Um vinho especial","De preferência de uma safra marcante pro casal."),
("Taças gravadas com os nomes","Pro brinde da festa."),
("Almoço de família com brinde","Todas as gerações juntas."),
("Livro com a história do casal","Escrito ou gravado a partir das histórias que eles contam."),
("Vídeo com mensagens","De quem não pôde estar presente."),
("Quadro das Bodas de Vinho","Com os nomes e os mais de 25.500 dias juntos.")],
frases=[("Pro amor","Setenta anos e você ficou ainda melhor, como vinho bom. Feliz Bodas de Vinho."),
("Pros avós","Setenta anos de amor, e cada ano deixou vocês ainda mais especiais. Parabéns, vovô e vovó!"),
("Legenda curta","70 anos de casados. Safra rara. Bodas de Vinho 🍷"),
("Pro brinde","Um brinde a setenta anos de amor — e a todos nós, que nascemos dele."),
("Pros bisavós","Setenta anos juntos. Vocês são a história viva da nossa família.")],
comemorar=["Um almoço de família com um brinde especial.","Gravar as histórias do casal em vídeo pra família guardar.","Uma festa pequena e aconchegante na casa do casal.","Uma foto das cinco gerações, se possível."],
faq=[("70 anos de casados são bodas de quê?","Bodas de Vinho."),
("Como comemorar 70 anos de casamento?","Com algo tranquilo e cheio de afeto: almoço de família, brinde, vídeo com mensagens e um presente simbólico, como um quadro com os nomes e a data.")])

C[75] = dict(
intro="Setenta e cinco anos de casados são as <b>Bodas de Brilhante</b> (em algumas listas, de alabastro). Três quartos de século juntos.",
sig=["O brilhante é o diamante lapidado, a forma que faz a pedra refletir a luz ao máximo. Se o diamante celebra os sessenta anos, o brilhante celebra o que veio depois: o mesmo amor, agora lapidado por mais quinze anos, brilhando ainda mais.",
"Setenta e cinco anos de casamento é algo que pouquíssimas famílias chegam a ver. Cada comemoração é histórica."],
origem="As bodas de brilhante aparecem aos 75 anos nas listas brasileiras. Em alguns países, os 75 anos são as bodas de diamante. Casais que chegam aqui costumam ganhar homenagens da cidade, da igreja e até reportagens.",
presentes=[("Uma joia com brilhante","Simbólica, pra passar de geração em geração."),
("Uma homenagem pública","Na igreja, no clube ou na comunidade."),
("Fotos restauradas das sete décadas","Numa exposição na festa."),
("Um livro com a história do casal","Contado pelos filhos e netos."),
("Um encontro de família","Com todos os ramos da árvore genealógica."),
("Quadro das Bodas de Brilhante","Com os nomes e os mais de 27.000 dias juntos.")],
frases=[("Pro amor","Setenta e cinco anos e você continua sendo a luz da minha vida. Feliz Bodas de Brilhante."),
("Pros avós ou bisavós","Setenta e cinco anos de amor. Vocês são a prova de que o para sempre existe. Parabéns!"),
("Legenda curta","75 anos de casados. Brilho que não acaba. 💎"),
("Pro telão","Três quartos de século de um amor que deu origem a esta família inteira."),
("Pro cartão","Obrigado por setenta e cinco anos de mãos dadas.")],
comemorar=["Um encontro com todas as gerações da família.","Uma homenagem na comunidade onde o casal viveu.","Uma exposição de fotos das sete décadas.","Gravar um vídeo com o casal contando a própria história."],
faq=[("75 anos de casados são bodas de quê?","Bodas de Brilhante. Algumas listas trazem bodas de alabastro."),
("Qual a diferença entre bodas de diamante e de brilhante?","Diamante são os 60 anos; brilhante, o diamante lapidado, são os 75.")])
